#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Wechsle ins Git-Root-Verzeichnis
cd "$(git rev-parse --show-toplevel)"

# Führe commitlint mit dem absoluten Pfad und expliziter Konfiguration aus
/Users/benjaminpoersch/.nvm/versions/node/v20.19.2/bin/node node_modules/@commitlint/cli/cli.js --config commitlint.config.js --edit "$1"
