name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run Ruff
        run: ruff . --output-format=github
      - name: Run Mypy
        run: mypy .
      - name: Run Pytest
        env:
          PYTHONPATH: .
        run: pytest --cov=./ --cov-report=xml --cov-report=term --cov-fail-under=40
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.os }}
          path: coverage.xml
          retention-days: 7
      - name: Build Dist
        if: success()
        run: python -m build
      - name: Upload Dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist
          retention-days: 7
